// <auto-generated />
using EspadasApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EspadasApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("EspadasApi.Models.Espada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Durabilidade")
                        .HasColumnType("double");

                    b.Property<string>("Familia")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("Forca")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Espadas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Durabilidade = 100.0,
                            Familia = "Flame",
                            Forca = 71,
                            Nome = "Cimitarra"
                        },
                        new
                        {
                            Id = 2,
                            Durabilidade = 100.0,
                            Familia = "Dark",
                            Forca = 41,
                            Nome = "Alfange"
                        },
                        new
                        {
                            Id = 3,
                            Durabilidade = 94.209999999999994,
                            Familia = "Dark",
                            Forca = 65,
                            Nome = "Montante"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
